version: "3"

services:
  webserver:
    image: "konstatinkorobitsin/php-and-redis:1.1"
    container_name: webserver
    restart: always
    ports:
      - 8808:80
    volumes:
      - "./application/:/var/www"
      - "./application/public/:/var/www/html"
      - "./configs/php/php.ini:/usr/local/etc/php/php.ini"
      - "./configs/apache/apache2.conf:/etc/apache2/apache2.conf"
      - "./configs/apache/000-default.conf:/etc/apache2/sites-available/000-default.conf"

  redis:
    image: redis:7.0.11-alpine
    container_name: redis
    restart: always
    #    ports:
    #      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis:/data

volumes:
  db_volume:
  redis: